# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: biphenyl.org
email: mira@dinogod.com
description: > # this means to ignore newlines until "baseurl:"
  Aromatic, organic, no longer associated with persistent environmental toxins?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmechtley.github.io" # the base hostname & protocol for your site
mastodon_url: "mastodon.gamedev.place/@biphenyl"
github_username: mmechtley
ads_query: 
    text: "M. Mechtley @ ADS"
    query: "author:\"Mechtley, M.\""
    

permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false
highlighter: rouge
